CREATE TYPE "public"."bg_color" AS ENUM('red', 'orange', 'yellow', 'green', 'blue', 'white', 'black', 'gray', 'purple', 'pink', 'brown', 'cyan', 'teal', 'transparent');--> statement-breakpoint
CREATE TYPE "public"."color" AS ENUM('red', 'orange', 'yellow', 'green', 'blue', 'white', 'black', 'gray', 'purple', 'pink', 'brown', 'cyan', 'teal', 'transparent');--> statement-breakpoint
CREATE TYPE "public"."font_size" AS ENUM('xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl');--> statement-breakpoint
CREATE TYPE "public"."font_style" AS ENUM('normal', 'italic', 'oblique');--> statement-breakpoint
CREATE TYPE "public"."font_weight" AS ENUM('thin', 'extralight', 'light', 'normal', 'medium', 'semibold', 'bold');--> statement-breakpoint
CREATE TYPE "public"."heading_variant" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');--> statement-breakpoint
CREATE TYPE "public"."list_type" AS ENUM('ordered', 'unordered', 'numbered');--> statement-breakpoint
CREATE TABLE "todo-agent_block" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo-agent_block_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"text" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"checkboxes" integer,
	"listItems" integer,
	"headings" integer,
	"paragraphs" integer
);
--> statement-breakpoint
CREATE TABLE "todo-agent_checkbox" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo-agent_checkbox_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"text" text,
	"checked" boolean DEFAULT false,
	"fontSize" "font_size" DEFAULT 'md',
	"fontWeight" "font_weight" DEFAULT 'normal',
	"color" "color" DEFAULT 'black',
	"bgColor" "bg_color" DEFAULT 'transparent',
	"fontStyle" "font_style" DEFAULT 'normal',
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "todo-agent_heading" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo-agent_heading_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"text" text,
	"variant" "heading_variant" DEFAULT 'h1',
	"fontSize" "font_size" DEFAULT '2xl',
	"fontWeight" "font_weight" DEFAULT 'bold',
	"color" "color" DEFAULT 'black',
	"bgColor" "bg_color" DEFAULT 'transparent',
	"fontStyle" "font_style" DEFAULT 'normal',
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "todo-agent_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo-agent_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"text" text,
	"url" text,
	"fontSize" "font_size" DEFAULT 'md',
	"fontWeight" "font_weight" DEFAULT 'medium',
	"color" "color" DEFAULT 'blue',
	"bgColor" "bg_color" DEFAULT 'transparent',
	"fontStyle" "font_style" DEFAULT 'italic',
	"underline" boolean DEFAULT true,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "todo-agent_list" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo-agent_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"text" text,
	"fontSize" "font_size" DEFAULT 'md',
	"fontWeight" "font_weight" DEFAULT 'normal',
	"color" "color" DEFAULT 'black',
	"bgColor" "bg_color" DEFAULT 'transparent',
	"fontStyle" "font_style" DEFAULT 'normal',
	"listType" "list_type" DEFAULT 'unordered',
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "todo-agent_page" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo-agent_page_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"blocks" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "todo-agent_paragraph" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo-agent_paragraph_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"text" text,
	"fontSize" "font_size" DEFAULT 'md',
	"fontWeight" "font_weight" DEFAULT 'normal',
	"color" "color" DEFAULT 'black',
	"bgColor" "bg_color" DEFAULT 'transparent',
	"fontStyle" "font_style" DEFAULT 'normal',
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "todo-agent_block" ADD CONSTRAINT "todo-agent_block_checkboxes_todo-agent_checkbox_id_fk" FOREIGN KEY ("checkboxes") REFERENCES "public"."todo-agent_checkbox"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "todo-agent_block" ADD CONSTRAINT "todo-agent_block_listItems_todo-agent_list_id_fk" FOREIGN KEY ("listItems") REFERENCES "public"."todo-agent_list"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "todo-agent_block" ADD CONSTRAINT "todo-agent_block_headings_todo-agent_heading_id_fk" FOREIGN KEY ("headings") REFERENCES "public"."todo-agent_heading"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "todo-agent_block" ADD CONSTRAINT "todo-agent_block_paragraphs_todo-agent_paragraph_id_fk" FOREIGN KEY ("paragraphs") REFERENCES "public"."todo-agent_paragraph"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "todo-agent_page" ADD CONSTRAINT "todo-agent_page_blocks_todo-agent_block_id_fk" FOREIGN KEY ("blocks") REFERENCES "public"."todo-agent_block"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "block_text_idx" ON "todo-agent_block" USING btree ("text");--> statement-breakpoint
CREATE INDEX "checkbox_text_idx" ON "todo-agent_checkbox" USING btree ("text");--> statement-breakpoint
CREATE INDEX "heading_text_idx" ON "todo-agent_heading" USING btree ("text");--> statement-breakpoint
CREATE INDEX "link_text_idx" ON "todo-agent_link" USING btree ("text");--> statement-breakpoint
CREATE INDEX "list_text_idx" ON "todo-agent_list" USING btree ("text");--> statement-breakpoint
CREATE INDEX "page_name_idx" ON "todo-agent_page" USING btree ("name");--> statement-breakpoint
CREATE INDEX "paragraph_text_idx" ON "todo-agent_paragraph" USING btree ("text");