ALTER TABLE "todo-agent_block" ALTER COLUMN "text" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_checkbox" ALTER COLUMN "text" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_checkbox" ALTER COLUMN "checked" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_checkbox" ALTER COLUMN "fontSize" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_checkbox" ALTER COLUMN "fontWeight" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_checkbox" ALTER COLUMN "color" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_checkbox" ALTER COLUMN "bgColor" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_checkbox" ALTER COLUMN "fontStyle" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_heading" ALTER COLUMN "text" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_heading" ALTER COLUMN "variant" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_heading" ALTER COLUMN "fontSize" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_heading" ALTER COLUMN "fontWeight" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_heading" ALTER COLUMN "color" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_heading" ALTER COLUMN "bgColor" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_heading" ALTER COLUMN "fontStyle" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "text" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "url" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "fontSize" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "fontWeight" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "color" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "bgColor" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "fontStyle" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_link" ALTER COLUMN "underline" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_list" ALTER COLUMN "text" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_list" ALTER COLUMN "fontSize" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_list" ALTER COLUMN "fontWeight" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_list" ALTER COLUMN "color" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_list" ALTER COLUMN "bgColor" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_list" ALTER COLUMN "fontStyle" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_list" ALTER COLUMN "listType" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_page" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_paragraph" ALTER COLUMN "text" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_paragraph" ALTER COLUMN "fontSize" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_paragraph" ALTER COLUMN "fontWeight" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_paragraph" ALTER COLUMN "color" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_paragraph" ALTER COLUMN "bgColor" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "todo-agent_paragraph" ALTER COLUMN "fontStyle" SET NOT NULL;